### ISSUE TITLE
Thelio Graphics Subcommands

### ISSUE THREAD

**Issue by cwmke** [szydell/system76-power#23]
Just want to offer a big thanks for porting all of these to Fedora. You saved me a great deal of time and effort. I can confirm they are also working for the Thelio desktop. 

I purchased a AMD desktop. For the `graphics` subcommands, does system76 not provide an AMD option?

**Comment by szydell** [comment]
@cwmke thanks for confirming, and sorry I missed that question before.

I do not found an AMD option in this software. If you need this feature, please contact its makers. I am just recompiling it for Fedora. :)
