### ISSUE TITLE
Malformed XML in com.system76.PowerDaemon.conf causing boot issues

### ISSUE THREAD

**Issue by ghost** [szydell/system76-power#56]
I'm reporting this issue on behalf of one of our System76 customers running Fedora 39 with the system76-power packages installed:

> I've been running Fedora for years now and am on Fedora 39. After doing a regular update, the whole dbus pam system failed. I could not get to a virtual console or login with Wayland. I could do an X11 login and tracked the problem down to malform XML in the file:
/usr/share/dbus-1/system.d/com.system76.PowerDaemon.conf

> Manually removing the "<<<<<<< HEAD", "=======" and ">>>>>>> upstream/master" lines from the file and rebooting fixed the problem.

> Also, at the Grub startup screen I could not move the cursor with my keyboard up and down arrow keys to selete an older kernel. This would be a different problem, but my guess is its related to several firmware updates that were a part of the latest Fedora 38 update vis dnf.

> #inix
CPU: 6-core AMD Ryzen 5 5600X (-MT MCP-) speed/min/max: 2450/2200/4650 MHz
Kernel: 6.8.10-200.fc39.x86_64 x86_64 Up: 23m Mem: 3.24/31.27 GiB (10.4%)
Storage: 5.69 TiB (27.7% used) Procs: 381 Shell: Bash inxi: 3.3.34

**Comment by szydell** [comment]
Thanks for the report.

Issue fixed in the 1.2.0-2 version and released on 23rd of May 2024.
